### ISSUE TITLE
Port to Firefox

### ISSUE THREAD

**Issue by beatgammit** [rhollister/goodreads#11]
I use Firefox primarily, so it would be awesome if you could port it.

If you're not interested, I might take a crack at it.

**Comment by rhollister** [comment]
A port is now available under firefox_addon/. Very shortly FIrefox is also going to support WebExtension which will allow Chrome Extensions to work as-is in Firefox. When that happens I'm hoping to have an official version.

**Comment by gavinr** [comment]
It looks like WebExtensions are now available: http://arewewebextensionsyet.com ... is it still advisable to use the `firefox_addon` folder here?

Thanks for the great extension!

**Comment by beatgammit** [comment]
@rhollister Firefox 57 is now released, which *only* allows WebExtension addons. Have you tried getting this to work on Firefox? I could for it if you're not interested in maintaining it on Firefox long term, or if you are, I could try send a PR with any changes needed to work on Firefox.

**Comment by gavinr** [comment]
I ran the CRX file through here https://www.extensiontest.com and it says it's compatible. Looks like the first update is that this plugin must switch to the "[options framework v2](https://developer.chrome.com/extensions/optionsV2#migration)" (in other words, use `options_ui` instead of [options_page](https://github.com/rhollister/goodreads/blob/master/manifest.json#L16) because that's the only one Firefox supports (https://bugzilla.mozilla.org/show_bug.cgi?id=1212684)

More info on porting: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension
