### ISSUE TITLE
Finding your overdrive URL is still problematic

### ISSUE THREAD

**Issue by auspex** [rhollister/goodreads#2]
The instructions for finding your library's overdrive URL don't work for my library. Their overdrive domain is **digitalmedia.halifaxpubliclibraries.ca**, which is a **CNAME** to **halifax.lib.overdrive.com**. The Overdrive search page only ever gives me the **.ca** domain and searching the contents of the library's Overdrive page never shows a **lib.overdrive.com** address—they're all **libraryreserve.cdn.overdrive.com**.

Now, I can manually use dig/nslookup on my own system to find that CNAME—how about using an AJAX call to a DNS service. This works nicely:

```
http://api.statdns.com/digitalmedia.halifaxpubliclibraries.ca/cname
```

returning

```
{
    "question": [
        {
            "name": "digitalmedia.halifaxpubliclibraries.ca.",
            "type": "CNAME",
            "class": "IN"
        }
    ],
    "answer": [
        {
            "name": "digitalmedia.halifaxpubliclibraries.ca.",
            "type": "CNAME",
            "class": "IN",
            "ttl": 10646,
            "rdlength": 27,
            "rdata": "halifax.lib.overdrive.com."
        }
    ]
}
```

**Comment by rhollister** [comment]
That's a fantastic idea! I had limited it so much because I really wanted to not ask for permission to all websites. It still really bugs me how non-user friendly the current version is.

That'll definitely be a feature in the next release!

**Comment by auspex** [comment]
Ah! I hadn't actually worked out yet why you even needed the overdrive URL rather than the library's domain, but I can see your issue.

**Comment by rhollister** [comment]
I added a major update that allows users to just click the map pin on Overdrive's library search map to add to their list. If the library doesn't have a standard URL it then does a DNS lookup to get it. Let me know what you think!

**Comment by auspex** [comment]
That doesn't work for me¸and I know it won't work for my mother's library (which doesn't show up on the Overdrive search at all—but I suspect that one might always be problematic).  It's possible that it's because I'm already set up, but when I installed the latest version I immediately saw:
`Setup complete! Go to your to-read bookshelf to see which books are available!`
but on the to-read shelf, it never showed as even loading the Overdrive column.

I can't enter anything in the Manual configuration.

When I go to the Overdrive map and click on the library location, then click on `Add this library to Available Goodreads`, I briefly see `Remove undefined from Available Goodreads` before it snaps back to `Add this library…`.

**Comment by rhollister** [comment]
1) Try searching for your mother's library by name instead of by location. Does that find it? I'll add something with that suggestion as well.

2) Could you explain the behavior for how you're not able to enter anything in the Manual Configuration? Are the input fields disabled? Or when you click Save nothing happens?

3) Are you running a developer version of the extension at the same time as the Chrome Store version? I just experienced the same behavior with both enabled. One has the library saved so it changes the text to "Remove library", the other doesn't have it saved so it changes the text back to "Add library", and they fight back and forth.

**Comment by auspex** [comment]
No, the problem with my mother's library is that it is part of a large
association of libraries (they say 27 regional libraries and 180+ branches—
http://olco.canlib.ca/), and Overdrive doesn't seem to know the locations
of even the regional libraries. So it would need to be input manually,
though I still haven't managed to figure out what the Overdrive URL would
be.

For manual entry (sorry, "doesn't work" is never a good bug report—I know
better!): _Libraries to search_: is always disabled. _Library Name_ is
usable, but I can't find anything that I can put in there that does
anything. _Overdrive URL_ needs to be a _.lib.overdrive.com
http://lib.overdrive.com_ URL which seems pointless now that you are
actually looking up non-overdrive domain names.

No, I'm not running a developer version of that extension at the same time,
though I am running one cloned off yours that is trying to do lookups on
the paper-book library holdings. I've changed its name and ID but I'll try
deleting it and see if that helps.

derek

**Comment by auspex** [comment]
I removed my extension and have the same problem with the library never getting set from the map.

I seem to be getting some results from manual configuration, but the UI is weak.  I gather, now, that I have to set the `Overdrive URL`, and that automatically updates the `Libraries to search` Textarea. So, move `Libraries to search` _after_  `Overdrive URL`, and make it more obvious that it is not intended to be manually entered. There's still no indication of what should be in `Library Name`—I managed to get two entries configured for `halifax.lib.overdrive.com` with different names, and on the book shelf page I saw _identical_ duplicate entries: both labelled with the second `Library Name`. It's also not obvious that the `Delete` button applies to `Libraries to search`—attach the `Add` button to `Overdrive URL` but the `Delete` button to  `Libraries to search`.

**Comment by rhollister** [comment]
1. Sorry I was not clear, what I meant is changing the "Search By" type from "Location" to "Name". Searching for libraries without locations works for me, does it work for you as well?
2. The OD URL is still necessary because I didn't want to rely totally on the statdns. If I was able to verify that every site reacted the same way (and would continue in the future), then I wouldn't tell the user about it at all.

In fact, just tonight when doing testing for Halifax I found a library that has a null answer defined: sovalue.org (http://api.statdns.com/sovalue.org/cname)

The manual entry is meant as a last-ditch effort.

I pushed an update to git if you want to give it a try. I'll hold off on pushing the update to hear what you think.

While I meant the UI to be minimalistic, I tried making the UI a little more clear. I agree with your point that the workflow was out of order. Is it better now? Any suggestions?

**Comment by auspex** [comment]
For the life of me, I'm not sure what Overdrive means by "location" and "name", either.  I find that often I can only find a library on that page by clicking on the map. Looking for my mother's library, I VPN'd to Chicago and dragged the map all the way across Lakes Michigan and Huron (and it doesn't let you zoom out very far)!

I can understand always storing the canonical name, but it should still be possible, if you have to enter a manual value, to enter your library's domain and try the CNAME lookup.

Unfortunately, sovalue.org demonstrates that there's always more than one way to redirect web traffic:

```
$ wget http://sovalue.org/
--2015-06-16 10:47:43--  http://sovalue.org/
Resolving sovalue.org (sovalue.org)... 50.63.202.22
Connecting to sovalue.org (sovalue.org)|50.63.202.22|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://sovalue.lib.overdrive.com [following]
--2015-06-16 10:47:44--  http://sovalue.lib.overdrive.com/
```
