### ISSUE TITLE
Hide the "not found"s

### ISSUE THREAD

**Issue by metafarion** [rhollister/goodreads#36]
The plugin works great for me, but the "not found" result seems unnecessary.  I would like to be able to have it simply omit the libraries that don't have a given title, rather than showing me a list of "not found"s, each of which takes up more vertical space on the page.

**Comment by gavinr** [comment]
I personally like the "not founds" so I know that the extension is working and I know when it's done searching. Maybe this could be a setting though ("Hide 'Not Found' Messages": checkbox true/false)

**Comment by metafarion** [comment]
Or perhaps more robust output filtering in general.  There are definitely be times I'd ONLY want to see the Availables, or only the entries with a hold list shorter than X, or audiobooks only.  Things of that nature.

**Comment by rhollister** [comment]
Great ideas. @gavinr's explanation is exactly why I had it in there. I'll add an option to hide it.

If either of you have time, checkout the extension on Firefox Mobile on your phone. I was thinking of transitioning the desktop version to a similar results layout. When there are multiple libraries, each result would also have a header of the library it came from. 

Also I'm thinking about instead of showing holds showing a "holds quotient" / score to make it easier to determine which to checkout. The result list would say something like "3.2 per hold" and the hover over would show the exact breakout "16 waiting on 5 copies". 

Recently I was trying to checkout a very very popular book (each library had 20-200 holds on 1-30 copies) and it was really difficult to figure out at a glance which library was the best to put a hold on.

**Comment by metafarion** [comment]
The holds quotient is a sweet idea.  I do like being able to see the library name listed, but this layout still has the potential to make the listing very tall with a lot of white space.  Here's an example with three library cards
![screenshot_2019-01-04-20-44-10](https://user-images.githubusercontent.com/2903603/50719629-dbaf8d00-1064-11e9-8942-8bbcb86bf0d1.png)
It might not seem so bad when looking at a single book, but in a list it creates a lot of extra scrolling. 
 The white space ratio is even higher on a desktop browser.  There must be a more efficient way to display the results.

**Comment by rhollister** [comment]
I just updated the design entirely for 5.0.0 since implementing the "estimatedWait" field in the API. Results should be more accurate, and links also default to Libby. Also added imports/export of settings.
