### ISSUE TITLE
Item match is not always correct.

### ISSUE THREAD

**Issue by zanymuzik** [rhollister/goodreads#39]
Here is an example where I was able to find a lot of matches based on the extension, except in reality, this book doesn't even exist on overdrive so all these matches are false.

https://www.goodreads.com/book/show/35049472-on-power
![Screen Shot](https://user-images.githubusercontent.com/38870465/88227402-698ca200-cc22-11ea-93c7-a17e16f0e341.png)

Overdrive inventory-
https://www.overdrive.com/creators/434776/robert-a-caro

I guess is that this problem is coming from stemming the title before the search.

**Comment by driscoll42** [comment]
I would suggest that to correct this, the extension should check if the full title exists in the title returned. However this would not be sufficient I have found due to various titles not always having the same title on Goodreads vs Overdrive when part of a series. (Another Example of this is "Thrawn: Treason" by Timothy Zahn - https://chipublib.overdrive.com/search/title?query=Thrawn&creator=Timothy+Zahn, https://www.goodreads.com/book/show/43160651-thrawn?ac=1&from_search=true&qid=qmrALSRCSj&rank=1) The extension removes everything after the colon which makes sense, however this results in numerous false positives.

A way to fix this I believe, is that on Overdrive returns more than just the title, it has a sorttitle and subtitle

"title":"Thrawn","sortTitle":"Thrawn Treason (Star Wars)", "subtitle":"Treason (Star Wars)"

By checking if the entirety of real title is in one of those three, it would work to get fewer false positives. It would fix the On Power issue. 

However the tradeoff of course is then you might miss some.

**Comment by rhollister** [comment]
Agreed. It was a very intentional choice to lean towards having false positives which can be annoying but ignored, rather than have false negatives which means never believing any "not found" result. If you have any other suggestions I'd be happy to try them out.

**Comment by driscoll42** [comment]
Perhaps an option to next to the "1 available" show the title/author? Then a user could filter without having to open each page to see what is there. I would think an option as the general user probably doesn't want that.

**Comment by rhollister** [comment]
Great solution. I'll add that as an option.
